class KeyNames:
    keyNameTemperature = 'temperature'
    keyNameHumidity = 'humidity'
    keyNameRainfall = 'rainfall'
    keyNameDists = 'dists'
    keyNameDistrict = 'district'
    keyNameState = 'state'
    keyNameStates = 'states'
    keyNameId = 'id'
    keyNameStateId = 'state_id'
    keyNameSeasons = 'seasons'
    keyNameCrops = 'crops'
    keyNameYield = 'yield'
    keyNameName = 'name'
    keyNameCropId = 'crop_id'

    queryParamState = 'state'
    queryParamDist = 'dist'
    queryParamStates = 'states'
    queryParamDists = 'dists'
    queryParamYears = 'years'
    queryParamParams = 'params'
    queryParamStateId = 'state_id'
    queryParamDistId = 'dist_id'
    queryParamSeason = 'season'
    queryParamCrop = 'crop'
